# Generated by Django 5.2.3 on 2025-06-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=300)),
                ('cpf', models.CharField(max_length=15)),
                ('num_CNH', models.CharField(max_length=15, null=True)),
                ('validade_CNH', models.DateField(help_text='Formato <em>YYYY-MM-DD</em>', null=True)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
