# Generated by Django 5.2.3 on 2025-07-02 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='idUsuario',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('idCarro', models.BigAutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=300)),
                ('cor', models.CharField(max_length=50)),
                ('fk_idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuarios')),
            ],
            options={
                'verbose_name_plural': 'Carros',
            },
        ),
        migrations.CreateModel(
            name='Estacionamentos',
            fields=[
                ('idEstacionamento', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_entrada', models.DateField(auto_now_add=True, help_text='Formato <em>YYYY-MM-DD</em>')),
                ('hora_entrada', models.TimeField(auto_now_add=True, help_text='Formato <em>YYYY-MM-DD</em>')),
                ('data_saida', models.TimeField(auto_now_add=True, help_text='Formato <em>YYYY-MM-DD</em>', null=True)),
                ('saida_saida', models.TimeField(auto_now_add=True, help_text='Formato <em>YYYY-MM-DD</em>', null=True)),
                ('fk_idCarro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.carros')),
            ],
            options={
                'verbose_name_plural': 'Estacionamentos',
            },
        ),
    ]
